/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kgpg.Key.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef KEYADAPTOR_H_52011149862140
#define KEYADAPTOR_H_52011149862140

#include <QtCore/QObject>
#include <QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kgpg.Key
 */
class KeyAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kgpg.Key")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kgpg.Key\" >\n"
"    <method name=\"showKeyInfo\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"keyID\" />\n"
"    </method>\n"
"    <method name=\"importRemoteKey\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"keyID\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"showOptions\" />\n"
"    <method name=\"showKeyServer\" />\n"
"    <method name=\"showKeyManager\" />\n"
"  </interface>\n"
        "")
public:
    KeyAdaptor(QObject *parent);
    virtual ~KeyAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool importRemoteKey(const QString &keyID);
    void showKeyInfo(const QString &keyID);
    void showKeyManager();
    void showKeyServer();
    void showOptions();
Q_SIGNALS: // SIGNALS
};

#endif
